require_relative '../lib/filetypes.rb'

describe 'Tests' do
  it 'test 1' do 
    files = ['Lakey - Better days.mp3', 
            'Wheathan - Superlove.wav', 
            'groovy jam.als', 
            '#4 final mixdown.als', 
            'album cover.ps', 
            'good nights.mp3']
    expect(solve(files)).to match_array(['.als', '.mp3'])

    files = ['Lakey - Better days.mp3', 
            'Fisher - Stop it.mp3', 
            'Fisher - Losing it.mp3', 
            '#4 final mixdown.als', 
            'album cover.ps', 
            'good nights.mp3']
    expect(solve(files)).to match_array(['.mp3'])

    # more sample tests
    expect(solve([])).to match_array([])
    expect(solve(['direful.pr', 'festive.html', 'historical.wav', 'holistic.mp3', 'impossible.jar', 'gentle.cpp', 'gleaming.xml', 'inconclusive.js', 'erect.jar', 'befitting.mp3', 'brief.wp', 'beautiful.jar', 'energetic.pt', 'careful.wp', 'defective.cpp', 'icky.wav', 'gorgeous.txt', 'good.pt', 'fat.pt', 'bored.als', 'adaptable.cpp', 'fumbling.exe', 'grieving.wp', 'efficient.wav', 'fearful.xml', 'damp.html', 'erect.exe', 'annoyed.xml', 'elderly.ala', 'far-flung.txt', 'careful.mp3', 'actually.pt', 'cynical.ala', 'complex.exe', 'extra-small.pt', 'enchanted.ala', 'amazing.html', 'bashful.h', 'hallowed.html', 'entertaining.html', 'bad.js', 'illegal.maya', 'deadpan.html', 'furtive.wp', 'hanging.css', 'drunk.py', 'capricious.wav', 'damaging.Ue4', 'cool.Ue4', 'ambitious.css', 'fortunate.wp', 'electric.mp3', 'crowded.txt', 'cooperative.html', 'graceful.pt', 'aboard.pt', 'exclusive.als', 'glossy.css', 'fluffy.pt', 'cluttered.txt', 'halting.cpp', 'glib.cpp', 'aback.pr', 'cynical.Ue4', 'chilly.xml', 'hideous.ala', 'finicky.txt', 'feigned.ala', 'better.Ue4', 'dear.py', 'available.xml', 'easy.pr', 'fine.mp3', 'cowardly.jar', 'incredible.css', 'adhesive.exe', 'energetic.mp3', 'harmonious.exe', 'general.als', 'condemned.als', 'flawless.als', 'curvy.h', 'ambitious.mp3', 'disillusioned.xml', 'bitter.h', 'hanging.wp', 'certain.cpp', 'flashy.html', 'cuddly.pr', 'cagey.Ue4', 'extra-small.pr', 'amuck.cpp', 'direful.html', 'delightful.als', 'helpless.h', 'foamy.mp3', 'enthusiastic.maya', 'good.maya', 'adhesive.css', 'imperfect.pr', 'bent.cpp', 'exultant.zbrush', 'adorable.mp3', 'clammy.maya', 'gaudy.pt', 'blushing.css', 'cuddly.Ue4', 'curved.py', 'boring.html', 'broken.txt', 'daily.jar', 'giddy.xml', 'curved.css', 'future.maya', 'graceful.css', 'guiltless.maya', 'gentle.cpp', 'few.css', 'calculating.txt', 'clear.pr', 'grey.py', 'entertaining.ala', 'elfin.txt', 'excited.js', 'abject.zbrush', 'best.js', 'boundless.wav', 'hurried.ala', 'delirious.cpp']
    )).to match_array(['.cpp', '.html'])
    expect(solve(['dramatic.txt', 'incompetent.jar', 'alcoholic.wp', 'clumsy.py', 'abject.h', 'boring.exe', 'aloof.pr', 'familiar.py', 'fanatical.py', 'ill-informed.html', 'fierce.pr', 'accurate.html', 'grotesque.pr', 'brown.py', 'courageous.pt', 'grouchy.jar', 'giant.pt', 'dirty.h', 'abaft.jar', 'enormous.zbrush', 'creepy.cpp', 'beneficial.py', 'absorbing.ala', 'heartbreaking.html', 'exclusive.js', 'fluttering.html', 'happy.als', 'fresh.pr', 'adamant.txt', 'awful.maya', 'frightening.maya', 'bizarre.html', 'efficacious.exe', 'illegal.wav', 'dizzy.js', 'gusty.wp', 'delightful.pt', 'full.als', 'chivalrous.xml', 'filthy.js', 'functional.jar', 'conscious.wav', 'feeble.exe', 'hilarious.cpp', 'earthy.py', 'handy.txt', 'hollow.cpp', 'aggressive.js', 'fat.h', 'drunk.exe', 'clear.h', 'easy.wav', 'eatable.pt', 'grumpy.css', 'empty.exe', 'brief.jar', 'aggressive.txt', 'aggressive.txt', 'gruesome.ala', 'awake.txt', 'apathetic.mp3', 'holistic.pt', 'embarrassed.css', 'flashy.maya', 'exultant.ala', 'exuberant.exe', 'graceful.pt', 'dependent.py', 'gigantic.wp', 'husky.js', 'immense.pr', 'defiant.cpp', 'cooperative.html', 'frantic.maya', 'abashed.css', 'dysfunctional.h', 'gusty.js', 'dynamic.txt', 'dreary.pt', 'giddy.ala', 'exciting.css', 'best.als', 'humdrum.css', 'busy.jar', 'frail.cpp', 'cagey.wav']
    )).to match_array(['.pt', '.py', '.txt'])
    expect(solve(['freezing.jar', 'frail.xml', 'available.txt', 'excited.als', 'godly.exe', 'fair.zbrush', 'abortive.Ue4', 'ill-fated.mp3', 'early.cpp', 'demonic.py', 'greedy.css', 'high.py', 'dry.xml', 'fascinated.html', 'humorous.zbrush', 'hilarious.pr', 'burly.pt', 'cumbersome.wp', 'elite.Ue4', 'equable.py', 'cold.h', 'discreet.wp', 'hard.mp3', 'aberrant.css', 'common.zbrush', 'fretful.maya', 'erect.js', 'good.maya', 'general.wav', 'complete.js', 'ad hoc.jar', 'healthy.mp3', 'bawdy.exe', 'impartial.py', 'hesitant.pt', 'erratic.css', 'agonizing.cpp', 'belligerent.html', 'cumbersome.Ue4', 'chilly.h', 'bustling.exe', 'curly.jar', 'gorgeous.py', 'friendly.txt', 'discreet.html', 'abhorrent.ala', 'awake.Ue4', 'good.Ue4', 'closed.html', 'gabby.py', 'imminent.js', 'combative.css', 'feigned.ala', 'elderly.ala', 'glamorous.h', 'dry.xml', 'illustrious.html', 'first.xml', 'conscious.xml', 'divergent.zbrush', 'doubtful.xml', 'big.ala', 'brief.h', 'clever.als', 'fierce.ala', 'adventurous.html', 'ashamed.jar', 'fast.cpp', 'fanatical.py', 'ambiguous.pr', 'efficient.txt', 'gullible.jar', 'ill-informed.cpp', 'capable.py', 'aboard.mp3', 'complete.als', 'helpful.maya', 'bizarre.css', 'filthy.js', 'hateful.Ue4', 'aback.wp', 'fertile.html', 'cloudy.als', 'comfortable.css', 'bustling.js', 'ad hoc.py', 'adorable.ala', 'frequent.als', 'flimsy.mp3', 'aboriginal.pt', 'blushing.h', 'feigned.py', 'bloody.py', 'hospitable.ala', 'extra-large.cpp', 'alike.exe', 'fine.js', 'confused.wav', 'bloody.wp', 'cumbersome.wav', 'harsh.mp3', 'crooked.css', 'equal.wav', 'drunk.als', 'general.cpp', 'grieving.css', 'certain.cpp', 'cumbersome.pt', 'different.txt', 'flat.h', 'cagey.h', 'enormous.wp', 'difficult.xml', 'furry.pt', 'enormous.exe', 'dramatic.h', 'brief.zbrush', 'elfin.zbrush', 'cumbersome.pt']
    )).to match_array(['.py'])
    expect(solve(['fresh.exe', 'groovy.pr', 'debonair.pr', 'hesitant.Ue4', 'curious.py', 'black.als', 'elderly.zbrush', 'harmonious.wav', 'different.cpp', 'ablaze.xml', 'abstracted.html', 'hollow.zbrush', 'familiar.xml', 'defiant.mp3', 'huge.exe', 'efficacious.html', 'aberrant.ala', 'better.js', 'glamorous.wp', 'glossy.cpp', 'gentle.jar', 'incandescent.exe', 'bashful.js', 'aware.pr', 'hellish.js', 'icky.cpp', 'chivalrous.pr', 'exotic.xml', 'grandiose.js', 'abrupt.html', 'bitter.mp3', 'chemical.xml', 'disagreeable.exe', 'far-flung.exe', 'acrid.wp', 'infamous.Ue4', 'hungry.xml', 'deadpan.h', 'equable.wp', 'hanging.txt', 'fanatical.Ue4', 'excellent.Ue4', 'grieving.js', 'brash.css', 'gullible.pr', 'acid.py', 'fragile.html', 'bewildered.jar', 'bored.zbrush', 'illustrious.zbrush', 'equal.cpp', 'female.wp', 'coordinated.cpp', 'elderly.txt']
    )).to match_array(['.cpp', '.exe', '.js', '.pr', '.xml'])
    expect(solve(['hanging.h', 'fixed.ala', 'first.pr', 'cooperative.cpp', 'elfin.zbrush', 'fair.pr', 'cool.css', 'highfalutin.py', 'alcoholic.maya', 'heady.cpp', 'befitting.wav', 'certain.jar', 'glistening.exe', 'attractive.wav', 'gruesome.wp', 'happy.txt', 'finicky.jar', 'clumsy.js', 'assorted.js', 'highfalutin.cpp', 'damaging.h', 'ethereal.xml', 'great.jar', 'dead.wp', 'acoustic.xml', 'devilish.css', 'curly.pt', 'exuberant.ala', 'flippant.wp', 'holistic.html', 'cut.txt', 'adamant.py', 'dashing.zbrush', 'conscious.wp', 'black-and-white.cpp', 'elated.pt', 'high-pitched.exe', 'flowery.xml', 'glib.wp', 'industrious.html', 'arrogant.zbrush', 'accessible.html', 'classy.jar', 'acceptable.maya', 'cynical.pt', 'erratic.pt', 'earthy.als', 'dramatic.als', 'bite-sized.py', 'ahead.xml', 'giddy.js', 'fortunate.txt', 'early.txt', 'imaginary.wav', 'cute.zbrush', 'graceful.html', 'far-flung.Ue4', 'goofy.exe', 'abundant.mp3', 'ambitious.txt', 'gigantic.jar', 'abashed.xml', 'guiltless.Ue4', 'adventurous.py', 'guarded.jar', 'extra-large.zbrush', 'filthy.h', 'easy.zbrush', 'glorious.als', 'detailed.pr', 'flashy.zbrush', 'breezy.als', 'faithful.py', 'curly.js', 'chief.js', 'concerned.js', 'cumbersome.zbrush', 'ahead.maya', 'berserk.cpp', 'deserted.pt', 'cool.zbrush', 'broken.cpp', 'glossy.pt', 'deep.xml', 'average.wav', 'dangerous.cpp', 'acrid.wav', 'dear.zbrush', 'deeply.pr', 'detailed.cpp', 'friendly.h', 'first.css', 'heady.exe', 'far-flung.als', 'erratic.mp3', 'exciting.pr']
    )).to match_array(['.zbrush'])
    expect(solve(['crazy.pr', 'black-and-white.als', 'illegal.wav', 'exultant.mp3', 'exotic.jar', 'capricious.pt', 'abundant.ala', 'eatable.zbrush', 'careful.py', 'godly.css', 'clever.txt', 'dusty.maya', 'awesome.zbrush', 'discreet.jar', 'creepy.h', 'fair.pt', 'descriptive.mp3', 'boundless.ala', 'berserk.xml', 'hungry.exe', 'awful.exe']
    )).to match_array(['.ala', '.exe', '.jar', '.mp3', '.pt', '.zbrush'])
  end
end